# Site settings
description: 'This is a project where my will, every day, i will watch at least a TED talk.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tedeveryday.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: hugocarreira
user_description: Only a little developer
user_title: Hugo Carreira
email: hugo.colombo23@gmail.com
twitter_username: hugo.colombo23
github_username:  hugocarreira
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
